### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by gautamgupta** [lionaneesh/Code-Pasty#11]
Suggested:

![UI](http://img826.imageshack.us/img826/2935/img20121113144526.jpg)

What say?

**Comment by lionaneesh** [comment]
Nice.

**Comment by lionaneesh** [comment]
@GautamGupta Do you want to work on it, or shall I do it?

**Comment by gautamgupta** [comment]
I will. :)

**Comment by lionaneesh** [comment]
@GautamGupta Any ETA on this one?

**Comment by gautamgupta** [comment]
Would have a draft by Dec 18, unless someone wants to beat me to it. :)

**Comment by lionaneesh** [comment]
@GautamGupta Deadline approaches tomorrow!

**Comment by lionaneesh** [comment]
@GautamGupta Ping!!!

**Comment by gautamgupta** [comment]
Github deleted all the images for this project :/

**Comment by lionaneesh** [comment]
Haha!
