### ISSUE TITLE
Rename "Code Pasty" to "CodePasty"

### ISSUE THREAD

**Issue by gautamgupta** [lionaneesh/Code-Pasty#15]

**Comment by lionaneesh** [comment]
It would be nice if you could add different colors to Code and Pasty. The 2 selected colors should blend in together well. Could you do that? If the selection of colors is difficult for you, paste some code on code pasty and see the colors used by the syntax highlighter for inspiration.

**Comment by gautamgupta** [comment]
To be taken care of in the new UI - #11.
